### PR TITLE
Add support for RegressionTest as a more comprehensive extension of ExtractionTest

### PR DESCRIPTION
**Pull request by ukengineer925**
This adds a more comprehensive extraction test, aka RegressionTest, to emissary.

See RegressionTest javadoc for more in-depth instructions, but to use with an existing ExtractionTest child, just extend RegressionTest instead, prepare the files in the format described (INITIAL_FORM.FINAL_FORM.OPTIONAL_COMMENT.dat) and remove existing XML files. Then override the generateAnswers() method to return true, and run the test class. This will generate new XML files in the correct location. Once you are happy with the XML files, just remove the generateAnswers() override and you're all set.

### CODE REVIEW

**Comment by ukengineer925** [comment]
Current revision now defaults to not serialising the dat file into the answer file, and being slightly clearer about what is open for overriding.

**Comment by andrewbp** [comment]
Looking through this. I want to try and use RegressionTest before giving approval.

**Comment by ukengineer925** [comment]
> Looking through this. I want to try and use RegressionTest before giving approval.

Sure - it was designed against one specific case so also interested to see how you find using it with something else.

**Comment by andrewbp** [comment]
Newest commit now works on my environment!

**Review by andrewbp — APPROVED** [review]

**Review by andrewbp — APPROVED** [review]
Still looks good!

**Review by smcgrattan — APPROVED** [review]
lgtm. used it to write a test. and son-of-a-gun, it worked.

**Review by andrewbp — DISMISSED** [review]
Builds do indeed succeed

**Comment by andrewbp** [comment]
Github claims there are conflicts but I don't see them when I test locally. I've verified that I have all 9 commits.

**Comment by ukengineer925** [comment]
Rebased against latest master.

**Review by drivenflywheel — APPROVED** [review]

**Review by smcgrattan — APPROVED** [review]

**Pull request merged**
