### PR TITLE
ci :: updating docker compose to allow for testing

### PR DESCRIPTION
**Pull request by dev-mlb**
These docker file updates are meant for GitHub actions. For the standard build, it starts a feeder and server and checks to see if they come up. This is the first step in a longer effort to test the Emissary stars tup and processes a file successfully.

### CODE REVIEW

**Comment by dev-mlb** [comment]
In action --
https://github.com/NationalSecurityAgency/emissary/actions/runs/9563667268/job/26362670922?pr=823

**Review by cfkoehler — APPROVED** [review]
Works as expected

**Review by cfkoehler — APPROVED** [review]

**Comment by jpdahlke** [comment]
> docker compose -f contrib/docker/docker-compose.ubi8.yml up --build --exit-code-from emissary-server

**Comment by cfkoehler** [comment]
> > docker compose -f contrib/docker/docker-compose.ubi8.yml up --build --exit-code-from emissary-server

Should we add this to the DEVELOPING.md

**Comment by DonResnik** [comment]
@dev-mlb is there any value in adding a README on how to use docker-compose?  I have a README for the burrito triton docker-compose effort on this branch  https://github.com/NationalSecurityAgency/burrito-grande/blob/2905-use-ImageMagick-for-image-id/contrib/docker/README.md  that might be pretty easy edit for emissary.

**Comment by DonResnik** [comment]
running ```docker compose -f contrib/docker/docker-compose.ubi8.yml up --build --exit-code-from emissary-server``` successfully started emissary server

**Review by DonResnik — COMMENTED** [review]
Consider adding README, detailed comment already added

**Comment by dev-mlb** [comment]
> > docker compose -f contrib/docker/docker-compose.ubi8.yml up --build --exit-code-from emissary-server

Whoops. First cut used the ubi8 yaml ... functionality moved to the ci yaml.

**Comment by dev-mlb** [comment]
@jpdahlke @cfkoehler @DonResnik Should we clean up the docker directory and remove some of the older files? Docker.ci contains ubi8, centos7, alpine, and the dev image all in one. I could remove those files and update the readme. Another option is to take this pr, and then I can target a clean up effort for Emissary 9?? Let me know your thoughts.

**Comment by DonResnik** [comment]
@dev-mlb  - I would be good with committing this PR as is if you make another ticket that includes cleaning up the docker files and adding the README.  I would be happy to work on that ticket if you don't have plans to do it already.

**Review by DonResnik — APPROVED** [review]

**Pull request merged**
