### PR TITLE
Improve performance of ShortNameComparator.

### PR DESCRIPTION
**Pull request by jdcove2**
This is an updated version of #135 .

### CODE REVIEW

**Review by drivenflywheel — CHANGES_REQUESTED** [review]
Do we think the performance improvements will be primarily speed, memory utilization, or both?

**Review by ldhardy — COMMENTED** [review]
Is there a trick to recreate the profile you describe in #135 ?  I've been trying to use the profiler on our main branch to observe the described behavior and I'm not having any luck.  I guess there have to be a lot of children extracted - I tried dumping in all kinds of archive input to see if I can see something similar on the profiler, but I'm not observing what you were.

**Review by ldhardy — APPROVED** [review]

**Comment by ldhardy** [comment]
> Yes, this optimization is designed for objects with a large number of children (i.e. 100,000 or more). Let me know if you would like me to generate an object for you.

Nah, I believe you.  It's not that big of a change really.

**Comment by ldhardy** [comment]
> Yes, this optimization is designed for objects with a large number of children (i.e. 100,000 or more). Let me know if you would like me to generate an object for you.

I meant the algorithm is basically the same, but yes, I can see how it's a less heavy handed implementation.

**Review by drivenflywheel — APPROVED** [review]

**Pull request merged**
