### PR TITLE
emissary transaction manager

### PR DESCRIPTION
**Pull request by ets-mlb**
Create an aspectj transaction manager to watch the data flow through Emissary.

### CODE REVIEW

**Comment by mjwall** [comment]
@ets-mlb a transaction manager is certainly a welcome addition.  Since there is no ticket, can you talk about why you choose aspectJ instead of just putting the code in the classes.  Didn't look like that many pointcuts from a quick review.

**Comment by ets-mlb** [comment]
We wanted to leave the transaction manager out of the main code and just use it as a watcher for now. AspectJ was chosen to weave the code into the existing code base, leaving minimal code changes to Emissary. This way we could integrate it in later, or easily rip it out if we don't like the implementation.

**Comment by ssfoster** [comment]
Any news on this PR?  Is the concern about adding another dependency?

**Comment by ets-mlb** [comment]
Newer pr will be submitted

**Pull request closed without merging**
