### PR TITLE
Make compatible with Java 11

### PR DESCRIPTION
**Pull request by fbruton**

### CODE REVIEW

**Comment by drivenflywheel** [comment]
Which JDK11 has this been tested with?  Do we have a prescribed release?  (OpenJDK, Amazon Corretto, ...)

**Comment by drivenflywheel** [comment]
What's the relationship between this PR and #122?  This PR was opened the same day that #122 was renamed from "Java 11 upgrade".   Is there a dependency between the two?

**Comment by drivenflywheel** [comment]
(Closed accidentally because this UI puts buttons with very different intents directly next to each other.  Now Reopened.)

**Comment by drivenflywheel** [comment]
I'll create a separate PR to address CodeQL findings.  The only outstanding issue I see is for this PR is that we need to update *contrib/docker/Dockerfile* to install `java-11-openjdk` instead of `java-1.8.0-openjdk`.  (I've tested this on my own workstation and Emissary works correctly.)

**Review by drivenflywheel — CHANGES_REQUESTED** [review]
Need to update the Dockerfile to specify `java-11-openjdk` instead of `java-1.8.0-openjdk`

**Comment by jpdahlke** [comment]
Closing in favor of #252

**Pull request closed without merging**
