### PR TITLE
Address error-prone ReturnMissingNullable and FieldMissingNullable

### PR DESCRIPTION
**Pull request by arp-0984**
Finishing up what I started during the snow week. Parent issue: https://github.com/NationalSecurityAgency/burrito-grande/issues/2600

### CODE REVIEW

**Comment by cfkoehler** [comment]
Found one in PickUpPlace:

```
[WARNING] /Users/connor/Projects/work/emissary/src/main/java/emissary/pickup/PickUpPlace.java:[167,23] [FieldMissingNullable] Field is assigned (or compared against) a definitely null value but is not annotated @Nullable
    (see https://errorprone.info/bugpattern/FieldMissingNullable)
```

**Comment by arp-0984** [comment]
> Found one in PickUpPlace:
> 
> ```
> [WARNING] /Users/connor/Projects/work/emissary/src/main/java/emissary/pickup/PickUpPlace.java:[167,23] [FieldMissingNullable] Field is assigned (or compared against) a definitely null value but is not annotated @Nullable
>     (see https://errorprone.info/bugpattern/FieldMissingNullable)
> ```

Weird, that one doesn't show up in the results for me. I'll add it anyway though

**Review by cfkoehler — DISMISSED** [review]

**Comment by sambish5** [comment]
So I actually have a few extra pop up for me when I run it.

**FieldMissingNullable:**
_MagicNumberFactory_
`[WARNING] /home/sambishop/emissary/src/main/java/emissary/util/magic/MagicNumberFactory.java:[21,50] [FieldMissingNullable] Field is assigned (or compared against) a definitely null value but is not annotated @Nullable
  Did you mean '@Nullable private static Map<String, Integer> typeMap = null;'?
`

**ReturnMissingNullable**
_MagicNumberFactory (x2)_
`[WARNING] /home/sambishop/emissary/src/main/java/emissary/util/magic/MagicNumberFactory.java:[390,8] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
  Did you mean '@Nullable private static byte[] resolveMask(String[] columns, MagicNumber item) {'?
`
`[WARNING] /home/sambishop/emissary/src/main/java/emissary/util/magic/MagicNumberFactory.java:[508,8] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
  Did you mean '@Nullable public static String resolveReverseDataType(int dataTypeId) {'?
`
_Stage (x3)_
`[WARNING] /home/sambishop/emissary/src/main/java/emissary/core/Stage.java:[64,12] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
  Did you mean 'public static @Nullable Stage getByName(String name) {'?
`
`[WARNING] /home/sambishop/emissary/src/main/java/emissary/core/Stage.java:[76,12] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
  Did you mean 'public static @Nullable Stage getByOrdinal(final int index) {'?
`
`[WARNING] /home/sambishop/emissary/src/main/java/emissary/core/Stage.java:[113,12] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
  Did you mean 'public static @Nullable Stage nextStageAfter(final String name) {'?
`

**Review by sambish5 — APPROVED** [review]
None show up for me now!

**Review by cfkoehler — APPROVED** [review]

**Review by cfkoehler — APPROVED** [review]

**Comment by jpdahlke** [comment]
Approving post-rebase/merge. Thanks @sambish5 for doing the heavy lifting.

**Review by jpdahlke — APPROVED** [review]

**Pull request merged**
