### PR TITLE
Removed DateTimeFormatParserLegacy

### PR DESCRIPTION
**Pull request by nixon124**

### CODE REVIEW

**Review by sambish5 — DISMISSED** [review]

**Review by arp-0984 — CHANGES_REQUESTED** [review]
There is also a reference to DateTimeFormatParserLegacy in a comment in DateTimeFormatParser.cfg. Can you remove this as well?

**Review by arp-0984 — APPROVED** [review]

**Review by sambish5 — APPROVED** [review]

**Review by sambish5 — DISMISSED** [review]

**Comment by arp-0984** [comment]
I'm not sure if something got messed up during the rebase, but I don't see all of the changes -- I only see removing the comment from DateTimeFormatParser.cfg

**Comment by jpdahlke** [comment]
- [ ] Awaiting internal testing to prove safe removal

**Comment by cfkoehler** [comment]
> * [ ]  Awaiting internal testing to prove safe removal

@nixon124 @jpdahlke Any update if this has been completed? Or blocked on other efforts

**Comment by jpdahlke** [comment]
Closing in favor of re-visiting on next major version

**Pull request closed without merging**
