### PR TITLE
jetty 11

### PR DESCRIPTION
**Pull request by dev-mlb**

### CODE REVIEW

**Comment by dev-mlb** [comment]
Still working on this:
```
[INFO] --- duplicate-finder-maven-plugin:1.5.1:check (default) @ emissary ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different resources in [org.glassfish.jersey.containers:jersey-container-jetty-http:3.1.3, org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty:3.1.3]:
[WARNING]   org/glassfish/jersey/jetty/internal/localization.properties
[WARNING] Found duplicate classes/resources in test classpath.
```

**Comment by dev-mlb** [comment]
> Still working on this:
> 
> ```
> [INFO] --- duplicate-finder-maven-plugin:1.5.1:check (default) @ emissary ---
> [INFO] Checking compile classpath
> [INFO] Checking runtime classpath
> [INFO] Checking test classpath
> [WARNING] Found duplicate and different resources in [org.glassfish.jersey.containers:jersey-container-jetty-http:3.1.3, org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty:3.1.3]:
> [WARNING]   org/glassfish/jersey/jetty/internal/localization.properties
> [WARNING] Found duplicate classes/resources in test classpath.
> ```

@jpdahlke  @fbruton Added `<ignoredResourcePatterns>` to the pom for localization.properties, not sure if this is the correct way to handle this or not.

**Comment by jpdahlke** [comment]
> > Still working on this:
> > ```
> > [INFO] --- duplicate-finder-maven-plugin:1.5.1:check (default) @ emissary ---
> > [INFO] Checking compile classpath
> > [INFO] Checking runtime classpath
> > [INFO] Checking test classpath
> > [WARNING] Found duplicate and different resources in [org.glassfish.jersey.containers:jersey-container-jetty-http:3.1.3, org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty:3.1.3]:
> > [WARNING]   org/glassfish/jersey/jetty/internal/localization.properties
> > [WARNING] Found duplicate classes/resources in test classpath.
> > ```
> 
> @jpdahlke @fbruton Added `<ignoredResourcePatterns>` to the pom for localization.properties, not sure if this is the correct way to handle this or not.

I think this seems reasonable. We might need to do that for some of our other resources as well.

**Comment by fbruton** [comment]
> > Still working on this:
> > ```
> > [INFO] --- duplicate-finder-maven-plugin:1.5.1:check (default) @ emissary ---
> > [INFO] Checking compile classpath
> > [INFO] Checking runtime classpath
> > [INFO] Checking test classpath
> > [WARNING] Found duplicate and different resources in [org.glassfish.jersey.containers:jersey-container-jetty-http:3.1.3, org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-jetty:3.1.3]:
> > [WARNING]   org/glassfish/jersey/jetty/internal/localization.properties
> > [WARNING] Found duplicate classes/resources in test classpath.
> > ```
> 
> @jpdahlke @fbruton Added `<ignoredResourcePatterns>` to the pom for localization.properties, not sure if this is the correct way to handle this or not.

I recommend the following approach instead that will scope the exclusion to the current conflicting dependencies.
```
        <plugin>
          <groupId>org.basepom.maven</groupId>
          <artifactId>duplicate-finder-maven-plugin</artifactId>
          <version>1.5.1</version>
          <configuration>
            <exceptions>
              <exception>
                <conflictingDependencies>
                  <dependency>
                    <groupId>org.glassfish.jersey.containers</groupId>
                    <artifactId>jersey-container-jetty-http</artifactId>
                    <version>${dep.jersey.version}</version>
                  </dependency>
                  <dependency>
                    <groupId>org.glassfish.jersey.test-framework.providers</groupId>
                    <artifactId>jersey-test-framework-provider-jetty</artifactId>
                    <version>${dep.jersey.version}</version>
                  </dependency>
                </conflictingDependencies>
                <resources>
                  <resource>org/glassfish/jersey/jetty/internal/localization.properties</resource>
                </resources>
              </exception>
            </exceptions>
            ```

**Review by fbruton — CHANGES_REQUESTED** [review]
Limit the scope of resource conflict exclusion.

**Review by fbruton — APPROVED** [review]

**Review by fbruton — APPROVED** [review]

**Pull request closed without merging**
